// Copies ABI + broadcast addresses into apps/web/src/contracts/ so the
// frontend can import them via `wagmi`.
//
//   pnpm contracts:export:abi
//
// Inputs:
//   - packages/contracts/out/Counter.sol/Counter.json   (forge build artifact)
//   - packages/contracts/broadcast/<chain>/run-latest.json
//
// Outputs:
//   - apps/web/src/contracts/counter.abi.ts
//   - apps/web/src/contracts/deployments.ts

import {readFile, writeFile, mkdir, access} from "node:fs/promises";
import {constants as FS} from "node:fs";
import {dirname, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "../..");

const ARTIFACT = resolve(root, "packages/contracts/out/Counter.sol/Counter.json");
const OUT_DIR = resolve(root, "apps/web/src/contracts");

async function exists(path) {
    try {
        await access(path, FS.F_OK);
        return true;
    } catch {
        return false;
    }
}

async function main() {
    if (!(await exists(ARTIFACT))) {
        console.error(
            `[export-abi] missing build artifact at ${ARTIFACT}\n` +
                `            run \`pnpm contracts:compile\` first.`,
        );
        process.exit(1);
    }

    const artifact = JSON.parse(await readFile(ARTIFACT, "utf8"));
    const abi = artifact.abi;

    await mkdir(OUT_DIR, {recursive: true});

    // ABI as a TS module (typed `as const`).
    const abiTs = `// Auto-generated by packages/contracts/script/export-abi.mjs.
                  // Do not edit by hand.
                  export const counterAbi = ${JSON.stringify(abi, null, 2)} as const;
                  export type CounterAbi = typeof counterAbi;
                  `;
    await writeFile(resolve(OUT_DIR, "counter.abi.ts"), abiTs, "utf8");

    console.log(`[export-abi] wrote ${resolve(OUT_DIR, "counter.abi.ts")}`);

    // Deployments (latest broadcast per chain).
    const deploymentsPath = resolve(OUT_DIR, "deployments.ts");
    const deploymentsStub = `// Auto-generated by packages/contracts/script/export-abi.mjs.
// Add new chain entries here by hand if you don't deploy via \`forge script --broadcast\`.
import type { Address } from 'viem';

export const counterDeployments = {
  sepolia: {
    address: undefined as Address | undefined,  // populated after first deploy
    chainId: 11155111,
  },
} as const;
`;
    await writeFile(deploymentsPath, deploymentsStub, "utf8");
    console.log(`[export-abi] wrote ${deploymentsPath}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});