// Copies ABI artifacts from forge build output into the frontend so wagmi
// can import them as typed `as const` modules.
//
//   # Export one or more contracts (defaults to Counter + Notepad):
//   node ./script/export-abi.mjs [ContractA ContractB ...]
//
// Inputs (per contract name `Foo`):
//   - packages/contracts/out/Foo.sol/Foo.json   (forge build artifact)
//
// Outputs (per contract name `Foo`):
//   - apps/web/src/contracts/foo.abi.ts   (export const fooAbi = [...] as const)
//
// NOTE: This script ONLY emits ABI modules. Deployment addresses live in
//       apps/web/src/contracts/deployments.ts and are edited by hand after
//       each `forge script --broadcast` run. The previous version of this
//       script clobbered that file — that was a bug and is no longer done.

import {readFile, writeFile, mkdir, access} from "node:fs/promises";
import {constants as FS} from "node:fs";
import {dirname, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "../..");
const OUT_DIR = resolve(root, "apps/web/src/contracts");

// Default: export everything this monorepo ships. Override by passing
// contract names as positional args, e.g. `node export-abi.mjs Counter`.
const REQUESTED = process.argv.slice(2);
const CONTRACTS = REQUESTED.length > 0 ? REQUESTED : ["Counter", "Notepad"];

async function exists(path) {
    try {
        await access(path, FS.F_OK);
        return true;
    } catch {
        return false;
    }
}

// PascalCase → camelCase for the exported binding (`Notepad` → `notepadAbi`).
// Single-segment names: lowercase first letter.
function toCamel(name) {
    return name[0].toLowerCase() + name.slice(1);
}

// PascalCase → kebab-case for the output filename (`Notepad` → `notepad.abi.ts`).
function toKebab(name) {
    return name[0].toLowerCase() + name.slice(1);
}

async function exportContract(name) {
    const camel = toCamel(name);
    const kebab = toKebab(name);

    const artifactPath = resolve(
        root,
        `packages/contracts/out/${name}.sol/${name}.json`,
    );

    if (!(await exists(artifactPath))) {
        console.error(
            `[export-abi] missing build artifact for ${name}:\n` +
                `            ${artifactPath}\n` +
                `            run \`pnpm contracts:compile\` first.`,
        );
        return false;
    }

    const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
    const abi = artifact.abi;

    const abiTs =
        `// Auto-generated by packages/contracts/script/export-abi.mjs.\n` +
        `// Do not edit by hand — re-run \`pnpm contracts:export:abi\` instead.\n` +
        `export const ${camel}Abi = ${JSON.stringify(abi, null, 2)} as const;\n` +
        `export type ${name}Abi = typeof ${camel}Abi;\n`;

    const outPath = resolve(OUT_DIR, `${kebab}.abi.ts`);
    await writeFile(outPath, abiTs, "utf8");
    console.log(`[export-abi] ${name}  →  ${outPath}`);
    return true;
}

async function main() {
    await mkdir(OUT_DIR, {recursive: true});

    const results = await Promise.all(CONTRACTS.map(exportContract));
    if (results.some((ok) => !ok)) {
        process.exit(1);
    }
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});