/**
 * 统一错误码契约。前端 + 后端共享此枚举，禁止在组件/handler 内联字符串。
 *
 * 命名约定：<DOMAIN>_<REASON>，SCREAMING_SNAKE_CASE。
 * HTTP status 由后端按 domain 决定，前端根据 code 决定 UX。
 */

export const ErrorCode = {
  // 通用
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL: 'INTERNAL',
  RATE_LIMITED: 'RATE_LIMITED',

  // 身份 / 鉴权
  INVALID_PRIVY_TOKEN: 'INVALID_PRIVY_TOKEN',
  PRIVY_TOKEN_EXPIRED: 'PRIVY_TOKEN_EXPIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  WALLET_ALREADY_BOUND: 'WALLET_ALREADY_BOUND',
  WALLET_SIGNATURE_INVALID: 'WALLET_SIGNATURE_INVALID',
  WALLET_NONCE_REUSED: 'WALLET_NONCE_REUSED',
  CANNOT_UNBIND_LAST_WALLET: 'CANNOT_UNBIND_LAST_WALLET',
  ROLE_CHANGE_REQUIRES_CONFIRM: 'ROLE_CHANGE_REQUIRES_CONFIRM',

  // 课程
  COURSE_STATE_CONFLICT: 'COURSE_STATE_CONFLICT',
  STALE_VERSION: 'STALE_VERSION',
  NOT_ENROLLED: 'NOT_ENROLLED',
  COMMENT_NOT_PURCHASED: 'COMMENT_NOT_PURCHASED',
  MEDIA_CHECKSUM_MISMATCH: 'MEDIA_CHECKSUM_MISMATCH',
  MEDIA_NOT_READY: 'MEDIA_NOT_READY',

  // 订单 / 链
  INTENT_EXPIRED: 'INTENT_EXPIRED',
  PRICE_VERSION_MISMATCH: 'PRICE_VERSION_MISMATCH',
  INVALID_TX_RECEIPT: 'INVALID_TX_RECEIPT',
  ALREADY_PURCHASED: 'ALREADY_PURCHASED',
  EVENT_REORGED: 'EVENT_REORGED',
  RPC_UNAVAILABLE: 'RPC_UNAVAILABLE',
  WRONG_CHAIN: 'WRONG_CHAIN',
  INSUFFICIENT_ALLOWANCE: 'INSUFFICIENT_ALLOWANCE',

  // 学习 / 证书
  PROGRESS_REGRESSION: 'PROGRESS_REGRESSION',
  ALREADY_COMPLETED: 'ALREADY_COMPLETED',
  CERTIFICATE_DUPLICATE: 'CERTIFICATE_DUPLICATE',
  MINT_NOT_AUTHORIZED: 'MINT_NOT_AUTHORIZED',
  MINT_FAILED: 'MINT_FAILED',

  // 权限 / 管理
  CONFIRM_TOKEN_INVALID: 'CONFIRM_TOKEN_INVALID',
  CHAIN_REPLAY_OUT_OF_RANGE: 'CHAIN_REPLAY_OUT_OF_RANGE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/** 默认 HTTP 状态映射（后端 reference）。 */
export const ErrorHttpStatus: Record<ErrorCodeValue, number> = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL: 500,
  RATE_LIMITED: 429,

  INVALID_PRIVY_TOKEN: 401,
  PRIVY_TOKEN_EXPIRED: 401,
  SESSION_EXPIRED: 401,
  WALLET_ALREADY_BOUND: 409,
  WALLET_SIGNATURE_INVALID: 422,
  WALLET_NONCE_REUSED: 409,
  CANNOT_UNBIND_LAST_WALLET: 409,
  ROLE_CHANGE_REQUIRES_CONFIRM: 428,

  COURSE_STATE_CONFLICT: 409,
  STALE_VERSION: 409,
  NOT_ENROLLED: 403,
  COMMENT_NOT_PURCHASED: 403,
  MEDIA_CHECKSUM_MISMATCH: 422,
  MEDIA_NOT_READY: 409,

  INTENT_EXPIRED: 410,
  PRICE_VERSION_MISMATCH: 409,
  INVALID_TX_RECEIPT: 422,
  ALREADY_PURCHASED: 409,
  EVENT_REORGED: 409,
  RPC_UNAVAILABLE: 503,
  WRONG_CHAIN: 409,
  INSUFFICIENT_ALLOWANCE: 409,

  PROGRESS_REGRESSION: 409,
  ALREADY_COMPLETED: 409,
  CERTIFICATE_DUPLICATE: 409,
  MINT_NOT_AUTHORIZED: 422,
  MINT_FAILED: 502,

  CONFIRM_TOKEN_INVALID: 428,
  CHAIN_REPLAY_OUT_OF_RANGE: 422,
};

export interface ApiError {
  code: ErrorCodeValue;
  message: string;
  requestId: string;
  details?: Record<string, unknown>;
}