// Auto-generated by packages/contracts/script/export-abi.mjs.
// Do not edit by hand — re-run `pnpm contracts:export:abi` instead.
export const chainlinkPriceOracleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "feedAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "maxAgeSeconds",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "description",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feed",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAggregatorV3"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestPrice",
    "inputs": [],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "decimals_",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "updatedAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxAge",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "IncompleteRound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAnswer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMaxAge",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StalePrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
export type ChainlinkPriceOracleAbi = typeof chainlinkPriceOracleAbi;
